name: release

on:
  push:
    tags:
      - 'v*'
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  "build":
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Check
      run:
        v=$(bash get_version.bash) || exit
        (($(git tag | grep "v$v" | wc -l) == 0)) || exit

    - name: Build
      run:
        bash gradlew build

    - name: Test
      run: ls build/libs
