name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - uses: actions/checkout@v2

    - run: git log -n 1

    - name: 'Get version'
      id: get-version
      run: |
        value=$(echo ${{ github.ref }} | perl -lpE 's|^refs/tags/v||')
        echo "$value"
        echo "::set-output name=value::$value"

    - name: 'Build'
      run: bash gradlew build

    - run: ls build/libs

    - id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: 'Upload asset: jar'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/InfluxDBUploaderMod-${{ steps.get-version.outputs.value }}.jar
        asset_name: InfluxDBUploaderMod-${{ steps.get-version.outputs.value }}.jar
        asset_content_type: application/java-archive

    - name: 'Upload asset: source'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/InfluxDBUploaderMod-${{ steps.get-version.outputs.value }}-sources.jar
        asset_name: InfluxDBUploaderMod-${{ steps.get-version.outputs.value }}-sources.jar
        asset_content_type: application/java-archive
